CREATE TABLE BOARD(
    BOARD_NO NUMBER(10) PRIMARY KEY,
    BOARD_NAME VARCHAR2(60) NOT NULL,
    BOARD_CONTENT VARCHAR2(1000),
    BOARD_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE BOARD_NO;

INSERT INTO BOARD VALUES(BOARD_NO.NEXTVAL, '공지사항 입니다.', '<요거 묵어봤는감> 에 오신걸 환영합니다', DEFAULT);
