--장바구니 테이블 생성
CREATE TABLE CART(
	CART_NO NUMBER(10) PRIMARY KEY,
	CUSTOMER_NO NUMBER(6) REFERENCES CUSTOMER(CUSTOMER_NO) NOT NULL,
	ITEM_NO NUMBER(8) REFERENCES ITEM(ITEM_NO) NOT NULL,
    CART_ITEM_COUNT NUMBER(3) NOT NULL
);

CREATE SEQUENCE CART_NO;

INSERT INTO CART VALUES(CART_NO.NEXTVAL, 1, 1, 1);
INSERT INTO CART VALUES(CART_NO.NEXTVAL, 2, 1, 32);
INSERT INTO CART VALUES(CART_NO.NEXTVAL, 3, 1, 87);
